---
# tasks file for docker

# 依存パッケージのインストール
- name: install docker dependency modules
  yum:
   name: ["yum-utils", "device-mapper-persistent-data", "lvm2"]
   state: latest
   update_cache: true
  become: yes
  become_method: sudo

# リポジトリ準備
- name: check docker repo file existance
  stat:
   path: /etc/yum.repos.d/docker-ce.repo # required. The full path of the file/object to get the facts of.
  register: docker_repo_exist

- name: install docker repo file
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: yes
  become_method: sudo
  when: not docker_repo_exist.stat.exists


# インストール
- name: install docker
  yum:
   name: ["docker-ce", "docker-ce-cli", "containerd.io"]
   state: latest
   update_cache: true
  become: yes
  become_method: sudo

# 起動
- name: ensure docker is running
  service:
   name: docker
   state: started
   enabled: yes
  become: yes
  become_method: sudo


- name: ensure docker is restarted
  service:
   name: docker
   state: restarted
   enabled: yes
  become: yes
  become_method: sudo