---
# tasks file for misc
# アプリインストール後のそのほかのタスク

# - name: modify /var/www permission
#   file:
#    path: /var/www
#    state: directory
#    mode: 0777
#   become: yes
#   become_method: sudo

# git 系セットアップ
- name: make git bare repository
  file:
   path: ~/git/web.git
   state: directory

- name: check bare repo is initialized
  stat:
   path: ~/git/web.git/HEAD
  register: git_bare_initialized


- name: make git bare repository
  command: git init --bare
  args:
   chdir: ~/git/web.git
  when: not git_bare_initialized.stat.exists

# git config
- name: git config mail
  command: "git config --global user.email {{mail_address}}"

- name: git config name
  command: "git config --global user.name {{user_name}}"

- name: git config color
  command: git config --global color.ui true

- name: git config quote
  command: git config --global core.quotepath false

# alias
- name: git status alias
  lineinfile:
   path: ~/.bashrc
   line: "alias gg='git status'"
   state: present
   insertafter: EOF
